security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        App\Entity\User:
            algorithm: auto
    providers:
        user_provider:
            id: App\Security\UserProvider


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            provider: user_provider
            form_login:
                login_path: login
                check_path: login
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator



    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
        #- { path: ^/users, roles: ROLE_API }
        #- { path: ^/orders, roles: ROLE_API }
       # - { path: ^/games, roles: ROLE_API }
        #- { path: /dashboard, roles: ROLE_API }




